package com.travelassistant.ui.viewmodel.search

import android.util.Log
import androidx.lifecycle.viewModelScope
import com.travelassistant.data.local.entity.SavedFlightSearchEntity
import com.travelassistant.data.local.entity.SearchDetails
import com.travelassistant.data.model.searchResults
import com.travelassistant.data.network.NetworkStateManager
import com.travelassistant.data.remote.dto.request.FlightSearchRequest
import com.travelassistant.data.remote.dto.request.SaveFlightSearchRequest
import com.travelassistant.data.repository.FlightResultRepository
import com.travelassistant.data.repository.FlightSearchRepository
import com.travelassistant.data.repository.SavedSearchRepository
import com.travelassistant.data.repository.impl.FlightSearchRepositoryImpl
import com.travelassistant.data.session.SessionManager
import com.travelassistant.ui.viewmodel.BaseUiViewModel
import com.travelassistant.ui.viewmodel.UiState
import com.travelassistant.util.Result
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject

@HiltViewModel
class SearchResultViewModel @Inject constructor(
    val flightSearchRepository: FlightSearchRepository,
    private val FlightSearchRepositoryImpl : FlightSearchRepositoryImpl,
    private val flightResultRepository: FlightResultRepository,
    private val networkStateManager: NetworkStateManager,
    private val savedSearchRepository: SavedSearchRepository,
    internal val sessionManager: SessionManager
) : BaseUiViewModel<SearchResultsState, SearchEvent>() {

    public override val _state = MutableStateFlow<UiState<SearchResultsState>>(UiState.Initial)
    val searchResultsState = MutableStateFlow<SearchResultsState>(SearchResultsState.Initial)

    val savedSearchStatus = MutableStateFlow<UiState<Boolean>>(UiState.Initial)

    override fun onEvent(event: SearchEvent) {
    }

    fun getSearchedFlights(searchDetails: SearchDetails) {
        viewModelScope.launch {
            searchResultsState.value = SearchResultsState.Loading
            delay(2000)
            // get flight form server

            val searchFlightsResponse = flightSearchRepository.searchFlights(
                FlightSearchRequest(
                    origin = searchDetails.origin,
                    destination = searchDetails.destination,
                    departureDate = searchDetails.departureDate,
                    returnDate = searchDetails.returnDate,
                    passengers = searchDetails.passengers,
                )
            )

            //api response
            // serverdan çekilen datalar buradan ekrana verilir
            // sorun yaşanırsa aşağıdaki yorum satırlarından test edilebilir.
            searchResultsState.value = when (searchFlightsResponse) {
                is Result.Success -> {
                    SearchResultsState.Success(searchFlightsResponse.data)
                }
                is Result.Error -> {
                    SearchResultsState.Error("Something Went Wrong")
                }
                Result.Loading -> {
                    SearchResultsState.Loading
                }
            }

            // mock data response
            /*
            searchResultsState.value = SearchResultsState.Success(flights = searchResults)
             */
        }
    }


    fun saveSearch(
        searchDetails: SearchDetails,
        maxStops: Int,
        priceRange: ClosedFloatingPointRange<Float>
    ) {
        viewModelScope.launch {

            val userDetails = sessionManager.getUserDetails()

            savedSearchStatus.tryEmit(UiState.Loading)

            /*
            // Create a new search entity
            val searchEntity = userDetails?.let { //this one
                SavedFlightSearchEntity(
                    id = "", // Will be generated by the repository
                    userId = it.id,
                    origin = searchDetails.origin,
                    destination = searchDetails.destination,
                    departureDate = searchDetails.departureDate,
                    returnDate = searchDetails.returnDate,
                    maxPrice = if (priceRange.endInclusive == Float.MAX_VALUE) Double.MAX_VALUE else priceRange.endInclusive.toDouble(),
                    maxStops = maxStops,
                    createdAt = System.currentTimeMillis(),
                    updatedAt = System.currentTimeMillis(),
                    lastSyncedAt = 0L,
                    passengers = searchDetails.passengers
                )
            }
            val entityId = searchEntity?.let { flightSearchRepository.insertSearch(it) }
            delay(600)
            if (entityId != null) {
                //savedSearchStatus.tryEmit(UiState.Success(data = entityId.isNotBlank()))

                val saveFlightRequest = SaveFlightSearchRequest(
                    origin = searchDetails.origin,
                    destination = searchDetails.destination,
                    departureDate = searchDetails.departureDate,
                    returnDate = searchDetails.returnDate,
                    adults = searchDetails.passengers // Or searchDetails.passengers.adults if it's an object
                )

                when (val backendResult = savedSearchRepository.saveUserFlightSearch(saveFlightRequest)) {
                    is Result.Success -> {
                        Log.i("SearchResultViewModel", "Search successfully saved to backend: ${backendResult.data}")
                        // Optionally, you could update the local entity's `lastSyncedAt` timestamp here
                        // and update it in the Room database.
                        // For example:
                        // searchEntity?.copy(lastSyncedAt = System.currentTimeMillis())?.let { updatedEntity ->
                        //     flightSearchRepository.updateSearch(updatedEntity) // You'd need an update method
                        // }
                    }
                    is Result.Error -> {
                        Log.e("SearchResultViewModel", "Failed to save search to backend: ${backendResult.message}")
                        // You might want to implement a retry mechanism or notify the user
                        // that the search is saved locally but failed to sync.
                    }

                    Result.Loading -> TODO()
                }

                savedSearchStatus.tryEmit(UiState.Success(data = entityId.isNotBlank()))
            } else {
                Log.e("SearchResultViewModel", "Failed to save search locally.")
                savedSearchStatus.tryEmit(UiState.Error(message = "Failed to save search locally."))
            }

             */

            /*
            // 1. Define the SimpleDateFormat instances
            // Input formatter for "May 31, 2025"
            // Using Locale.ENGLISH for month name parsing
            val inputSdf = SimpleDateFormat("MMM d, yyyy", Locale.ENGLISH)
            // Output formatter for "yyyy-MM-dd"
            val outputSdf = SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH) // Locale for output usually doesn't affect format like yyyy-MM-dd but good practice.

            // 2. Convert departureDate
            val formattedDepartureDate: String
            try {
                // Parse the input string to a java.util.Date object
                val dateObjDeparture: Date = inputSdf.parse(searchDetails.departureDate)
                    ?: throw NullPointerException("Input SDF parse returned null for departure date") // Should not happen with valid pattern unless input is null, but good to be safe
                // Format the Date object to the desired output string
                formattedDepartureDate = outputSdf.format(dateObjDeparture)
            } catch (e: Exception) { // Catch ParseException or any other exception
                Log.e("SearchResultViewModel", "Error parsing departureDate: ${searchDetails.departureDate}", e)
                savedSearchStatus.tryEmit(UiState.Error("Invalid departure date format."))
                return@launch // Stop execution if date parsing fails
            }

            // 3. Convert returnDate (handle nullable)
            val formattedReturnDate: String?
            if (searchDetails.returnDate != null) {
                try {
                    val dateObjReturn: Date = inputSdf.parse(searchDetails.returnDate)
                        ?: throw NullPointerException("Input SDF parse returned null for return date")
                    formattedReturnDate = outputSdf.format(dateObjReturn)
                } catch (e: Exception) {
                    Log.e("SearchResultViewModel", "Error parsing returnDate: ${searchDetails.returnDate}", e)
                    savedSearchStatus.tryEmit(UiState.Error("Invalid return date format."))
                    return@launch // Stop execution if date parsing fails
                }
            } else {
                formattedReturnDate = null
            }

             */

            // 1. Create the request DTO for the backend.
            //    Ensure date formats are "yyyy-MM-dd" as required by your DTO.
            //    Adjust `adults` mapping based on your `SearchDetails.passengers` structure.
            val saveFlightRequest = SaveFlightSearchRequest(
                origin = searchDetails.origin,
                destination = searchDetails.destination,
                departureDate = searchDetails.departureDate,
                returnDate = searchDetails.returnDate,
                adults = searchDetails.passengers // Or searchDetails.passengers.adults if it's a complex object
            )

            Log.d("SearchResultViewModel", "Attempting to save search to backend: $saveFlightRequest")

            // 2. Call the repository method to save to the backend.
            when (val backendResult = savedSearchRepository.saveUserFlightSearch(saveFlightRequest)) {
                is Result.Success -> {
                    val backendResponse = backendResult.data
                    Log.i("SearchResultViewModel", "Search successfully saved to backend: $backendResponse")

                    // 3. If backend save was successful, create the Room entity using the backend's response.
                    val searchEntity = userDetails?.let {
                        SavedFlightSearchEntity(
                            id = backendResponse.searchId.toString(), // Use ID from backend
                            userId = it.id,
                            origin = backendResponse.origin, // Use data from backend response for consistency
                            destination = backendResponse.destination,
                            departureDate = backendResponse.departureDate,
                            returnDate = backendResponse.returnDate,
                            // maxPrice and maxStops are not in SaveFlightSearchResponse, so use original inputs
                            maxPrice = if (priceRange.endInclusive == Float.MAX_VALUE) Double.MAX_VALUE else priceRange.endInclusive.toDouble(),
                            maxStops = maxStops,
                            createdAt = System.currentTimeMillis(), // Or a server-provided timestamp if available and preferred
                            updatedAt = System.currentTimeMillis(),
                            lastSyncedAt = System.currentTimeMillis(), // It's now synced
                            // For 'passengers', decide if you want to use the original searchDetails.passengers
                            // (which might have more detail like children/infants) or map from backendResponse.adults.
                            // If SavedFlightSearchEntity.passengers is complex, use searchDetails.passengers.
                            // If SavedFlightSearchEntity.passengers is just an Int for adults, use backendResponse.adults.
                            passengers = searchDetails.passengers // Assuming this is the desired structure for local entity
                        )
                    }

                    // 4. Save the entity (with the server-provided ID) to the local Room database.
                    try {
                        if (searchEntity != null) {
                            flightSearchRepository.insertSearch(searchEntity)
                        } // Assuming this handles insert/replace
                        if (searchEntity != null) {
                            Log.i("SearchResultViewModel", "Search entity saved to Room with ID: ${searchEntity.id}")
                        }
                        savedSearchStatus.tryEmit(UiState.Success(data = true)) // Overall success
                    } catch (e: Exception) {
                        Log.e("SearchResultViewModel", "Error saving search entity to Room: ${e.message}", e)
                        // Critical decision: Backend save succeeded, but local save failed.
                        // You might want a more specific error state or a sync mechanism.
                        // For now, report as an error, but acknowledge backend success in logs.
                        savedSearchStatus.tryEmit(UiState.Error("Saved to server, but failed to save locally: ${e.message}"))
                    }
                }
                is Result.Error -> {
                    Log.e("SearchResultViewModel", "Failed to save search to backend: ${backendResult.message}")
                    savedSearchStatus.tryEmit(UiState.Error("Failed to save search: ${backendResult.message}"))
                }

                Result.Loading -> TODO()
            }
        }
    }

}